---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.fullname" . }}-environment-{{ .Release.Revision }}
  labels:
    app.kubernetes.io/name: {{ include "helm.fullname" . }}
    helm.sh/chart: {{ include "helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
{{- range $name, $value := .Values.app.env }}
  {{ $name }}: "{{ $value | b64enc }}"
{{- end }}
