name: Publish docker image

on:
  push:
    branches:
      - main

jobs:
  date_sha_tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.image_tag.outputs.tag }}
    steps:
      - id: image_tag
        run: echo "::set-output name=tag::$(date +%s)-${{ github.sha }}"

  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/wepublish/reatch-sync:main-${{ needs.date_sha_tag.outputs.tag }}
